services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme:/acme
      - ./logs:/logs
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

  test_webapp:
    image: nginx:latest
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test_webapp.rule=Host(`nginx.${TRAEFIK_HOST}`)"
      - "traefik.http.routers.test_webapp.tls=true"
      - "traefik.http.routers.test_webapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.test_webapp.loadbalancer.server.port=80"

networks:
  traefik:
    external: true