global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: true
  insecure: false

log:
  level: INFO
  format: json
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        options: default

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_EMAIL}
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web